# Generated by Django 4.2.7 on 2026-02-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        help_text="Ej: Ortodoncia, Implante, Limpieza, etc.",
                        max_length=200,
                        verbose_name="Tipo de Tratamiento",
                    ),
                ),
                (
                    "dentist_responsible",
                    models.CharField(
                        max_length=200, verbose_name="Dentista Responsable"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de Sesiones"
                    ),
                ),
                (
                    "completed_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sesiones Completadas"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Total"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cantidad Pagada",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En Curso"),
                            ("completed", "Terminado"),
                            ("cancelled", "Cancelado"),
                            ("with_debt", "Con Adeudo"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción del Tratamiento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento",
                "verbose_name_plural": "Tratamientos",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_number",
                    models.PositiveIntegerField(verbose_name="Número de Sesión"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("comments", models.TextField(verbose_name="Comentarios del Doctor")),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="treatments.treatment",
                        verbose_name="Tratamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avance de Tratamiento",
                "verbose_name_plural": "Avances de Tratamiento",
                "ordering": ["-date", "-session_number"],
                "unique_together": {("treatment", "session_number")},
            },
        ),
        migrations.CreateModel(
            name="TreatmentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Foto Clínica"),
                            ("radiograph", "Radiografía"),
                            ("report", "Reporte"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Archivo",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="treatment_files/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="treatments.treatmentprogress",
                        verbose_name="Avance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Tratamiento",
                "verbose_name_plural": "Archivos de Tratamiento",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["patient", "status"], name="treatments__patient_32e7fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["start_date"], name="treatments__start_d_c80c65_idx"
            ),
        ),
    ]
