# Generated by Django 4.2.7 on 2026-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_income", "Ingresos Diarios"),
                            ("weekly_income", "Ingresos Semanales"),
                            ("monthly_income", "Ingresos Mensuales"),
                            ("daily_expenses", "Gastos Diarios"),
                            ("weekly_expenses", "Gastos Semanales"),
                            ("monthly_expenses", "Gastos Mensuales"),
                            ("common_treatments", "Tratamientos Más Comunes"),
                            ("patients_with_debt", "Pacientes con Adeudo"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        max_length=10,
                        verbose_name="Formato de Exportación",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="Archivo Generado",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos del Reporte"
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Generado por",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-generated_at"],
            },
        ),
    ]
