# Generated by Django 4.2.7 on 2026-02-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chronic_diseases",
                    models.TextField(
                        blank=True,
                        help_text="Diabetes, hipertensión, etc.",
                        null=True,
                        verbose_name="Enfermedades Crónicas",
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Medicamentos Actuales"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Medicamentos, materiales dentales, etc.",
                        null=True,
                        verbose_name="Alergias",
                    ),
                ),
                (
                    "previous_dental_treatments",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Tratamientos Dentales Previos",
                    ),
                ),
                ("smoking", models.BooleanField(default=False, verbose_name="Fumador")),
                (
                    "alcohol_consumption",
                    models.BooleanField(default=False, verbose_name="Consume Alcohol"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Adicionales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Médico",
                "verbose_name_plural": "Historiales Médicos",
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones Clínicas"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_notes",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Clínica",
                "verbose_name_plural": "Notas Clínicas",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Foto Clínica"),
                            ("radiograph", "Radiografía"),
                            ("pdf", "Documento PDF"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Archivo",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="clinical_files/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "date_taken",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Toma"
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Subido por"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "clinical_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="clinical.clinicalnote",
                        verbose_name="Nota Clínica",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_files",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Clínico",
                "verbose_name_plural": "Archivos Clínicos",
                "ordering": ["-date_taken", "-uploaded_at"],
            },
        ),
    ]
