# Generated by Django 4.2.7 on 2026-02-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("first_visit", "Primera Visita"),
                            ("follow_up", "Seguimiento"),
                            ("cleaning", "Limpieza"),
                            ("extraction", "Extracción"),
                            ("filling", "Empaste"),
                            ("root_canal", "Endodoncia"),
                            ("orthodontics", "Ortodoncia"),
                            ("implant", "Implante"),
                            ("emergency", "Emergencia"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Consulta",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("start_time", models.TimeField(verbose_name="Hora de Inicio")),
                ("end_time", models.TimeField(verbose_name="Hora de Fin")),
                (
                    "dental_unit",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Sillón 1, Sillón 2, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Unidad/Sillón",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("cancelled", "Cancelada"),
                            ("completed", "Completada"),
                            ("no_show", "No Asistió"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="Recordatorio Enviado"
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Recordatorio Enviado el"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Correo Electrónico"),
                        ],
                        max_length=20,
                        verbose_name="Método",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado el"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Exitoso")),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="appointments.appointment",
                        verbose_name="Cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recordatorio de Cita",
                "verbose_name_plural": "Recordatorios de Citas",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "start_time"], name="appointment_date_85ff09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "date"], name="appointment_patient_83aa7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
    ]
