# Generated by Django 4.2.7 on 2026-02-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("treatments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("materials", "Materiales"),
                            ("laboratory", "Laboratorio"),
                            ("rent", "Renta"),
                            ("salaries", "Sueldos"),
                            ("utilities", "Servicios"),
                            ("equipment", "Equipo"),
                            ("maintenance", "Mantenimiento"),
                            ("marketing", "Marketing"),
                            ("other", "Otros"),
                        ],
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Fecha del Gasto")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("card", "Tarjeta"),
                            ("check", "Cheque"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Proveedor"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número de Factura",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expense_date"], name="finances_ex_expense_6b57bf_idx"
                    ),
                    models.Index(
                        fields=["category", "expense_date"],
                        name="finances_ex_categor_6c92f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("card", "Tarjeta"),
                            ("check", "Cheque"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Fecha de Pago")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de transferencia, voucher, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Número de Referencia",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="treatments.treatment",
                        verbose_name="Tratamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_date"], name="finances_pa_payment_1d61c0_idx"
                    ),
                    models.Index(
                        fields=["patient", "payment_date"],
                        name="finances_pa_patient_9d9ac6_idx",
                    ),
                ],
            },
        ),
    ]
