# Generated by Django 4.2.7 on 2026-02-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Especialidad",
                    ),
                ),
                (
                    "professional_license",
                    models.CharField(max_length=100, verbose_name="Cédula Profesional"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre del Consultorio",
                    ),
                ),
                (
                    "clinic_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección del Consultorio"
                    ),
                ),
                (
                    "digital_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Firma Digital",
                    ),
                ),
                (
                    "clinic_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Logo del Consultorio",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biografía"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Doctor",
                "verbose_name_plural": "Perfiles de Doctores",
            },
        ),
    ]
