"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
import logging
from pathlib import Path
import dj_database_url

# Configure logging
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# GCS Storage Configuration Constants
DEFAULT_GCS_BUCKET_NAME = '3dy-backup'

# Import development GCS configuration
try:
    from _config.gcs_dev_config import GCS_DEV_CONFIG
except ImportError:
    GCS_DEV_CONFIG = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

DOMAIN = os.getenv("DOMAIN")
if not DOMAIN and not DEBUG:
    raise Exception("DOMAIN environment variable is required in production")

ALLOWED_HOSTS = []
if DEBUG:
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1", "0.0.0.0"])
else:
    if DOMAIN:
        ALLOWED_HOSTS.extend([
            DOMAIN,
            f"api.{DOMAIN}",
            f"www.{DOMAIN}",
        ])

# Dynamically find all apps in the backend folder
def find_apps(base_dir, exclude_dirs=None):
    exclude_dirs = exclude_dirs or []
    # Always exclude config directories to prevent them from being added as apps
    exclude_dirs = list(exclude_dirs) + ['_config']
    apps = []
    for item in os.listdir(base_dir):
        item_path = os.path.join(base_dir, item)
        if (
            os.path.isdir(item_path) and
            item not in exclude_dirs and
            os.path.isfile(os.path.join(item_path, '__init__.py'))
        ):
            apps.append(item)
    return apps

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'import_export',
    'django_celery_beat',
    'django_celery_results',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + find_apps(BASE_DIR)
if DEBUG:
    INSTALLED_APPS += ["django_extensions"]
else:
    # Production: Add storages for GCS backend
    INSTALLED_APPS += ["storages"]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = '_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if DEBUG:
    # Development: use PostgreSQL !
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }
else:
    # Production: Railway DATABASE_URL
    DATABASES = {
        "default": dj_database_url.config(
            default="postgres://user:password@host:5432/dbname",  # fallback if DATABASE_URL is missing
            conn_max_age=600,
            ssl_require=True,
        )
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_config/staticfiles')

# Media files configuration - GCS for production, local for development
# GCS Configuration - works in both development and production
# In development: Uses hardcoded credentials from gcs_dev_config.py
# In production: Uses environment variables
GCS_BUCKET_NAME = os.getenv('GCS_BUCKET_NAME')
GCS_PROJECT_ID = os.getenv('GCS_PROJECT_ID')

# Development: Use hardcoded GCS credentials for backup/restore operations
if DEBUG and GCS_DEV_CONFIG:
    # Override with hardcoded development credentials if not set via environment
    if not GCS_BUCKET_NAME and 'GCS_BUCKET_NAME' in GCS_DEV_CONFIG:
        GCS_BUCKET_NAME = GCS_DEV_CONFIG['GCS_BUCKET_NAME']
        logger.info(f"Using hardcoded GCS_BUCKET_NAME for development: {GCS_BUCKET_NAME}")

    if not GCS_PROJECT_ID and 'GCS_PROJECT_ID' in GCS_DEV_CONFIG:
        GCS_PROJECT_ID = GCS_DEV_CONFIG['GCS_PROJECT_ID']
        logger.info(f"Using hardcoded GCS_PROJECT_ID for development: {GCS_PROJECT_ID}")

    # Set credentials in environment for management commands
    if not os.getenv('GOOGLE_APPLICATION_CREDENTIALS_JSON') and 'GOOGLE_APPLICATION_CREDENTIALS_JSON' in GCS_DEV_CONFIG:
        os.environ['GOOGLE_APPLICATION_CREDENTIALS_JSON'] = json.dumps(GCS_DEV_CONFIG['GOOGLE_APPLICATION_CREDENTIALS_JSON'])
        logger.info("Using hardcoded GCS credentials for development")

# Use default bucket name if not provided
if not GCS_BUCKET_NAME:
    GCS_BUCKET_NAME = DEFAULT_GCS_BUCKET_NAME
    logger.warning(f"GCS_BUCKET_NAME not set, using default: {DEFAULT_GCS_BUCKET_NAME}")

# Path to service account credentials (JSON string from environment variable)
GCS_CREDENTIALS_JSON = os.getenv('GOOGLE_APPLICATION_CREDENTIALS_JSON')
GCS_CREDENTIALS = None

if GCS_CREDENTIALS_JSON:
    # Parse and validate credentials from JSON string
    try:
        parsed_creds = json.loads(GCS_CREDENTIALS_JSON)

        # Validate that parsed JSON contains required service account fields
        if isinstance(parsed_creds, dict):
            required_fields = ['type', 'project_id', 'private_key_id', 'private_key', 'client_email']
            missing_fields = [field for field in required_fields if field not in parsed_creds]

            if not missing_fields:
                GCS_CREDENTIALS = parsed_creds
            else:
                logger.warning(
                    "GOOGLE_APPLICATION_CREDENTIALS_JSON is missing required fields. "
                    "Please provide a valid service account JSON key file. "
                    "Credentials will not be available for GCS storage."
                )
        else:
            logger.warning(
                "GOOGLE_APPLICATION_CREDENTIALS_JSON is not a valid JSON object. "
                "Credentials will not be available for GCS storage."
            )
    except json.JSONDecodeError:
        logger.warning(
            "GOOGLE_APPLICATION_CREDENTIALS_JSON is not valid JSON. "
            "Please verify your credentials JSON string is properly formatted. "
            "Credentials will not be available for GCS storage."
        )
        GCS_CREDENTIALS = None
    except Exception:
        logger.warning(
            "Error processing GOOGLE_APPLICATION_CREDENTIALS_JSON. "
            "Credentials will not be available for GCS storage."
        )
        GCS_CREDENTIALS = None

# Note: File-based credentials via GOOGLE_APPLICATION_CREDENTIALS env var
# are handled automatically by Google Cloud libraries, not passed to OPTIONS
GCS_CREDENTIALS_FILE = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

# Validate that we have the required configuration
if not GCS_PROJECT_ID:
    if not DEBUG:
        logger.warning(
            "GCS_PROJECT_ID not set. GCS storage may not work correctly. "
            "Set GCS_PROJECT_ID environment variable to your Google Cloud project ID."
        )

if not GCS_CREDENTIALS and not GCS_CREDENTIALS_FILE:
    if not DEBUG:
        logger.warning(
            "No GCS credentials found! "
            "Set GOOGLE_APPLICATION_CREDENTIALS_JSON or GOOGLE_APPLICATION_CREDENTIALS. "
            "File uploads will fail without valid credentials."
        )

# Configure storage based on DEBUG mode
if DEBUG:
    # Development: Use local file storage for media files
    # GCS credentials are available for backup/restore commands
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # Production: Use Google Cloud Storage
    # Configure storage backends using STORAGES setting (Django 4.2+)
    # Note: credentials should be a dict from JSON parsing, or None to use default auth
    # File paths should not be passed directly - use GOOGLE_APPLICATION_CREDENTIALS env var
    # Only configure GCS if we have the minimum required settings (bucket and project)
    if GCS_BUCKET_NAME and GCS_PROJECT_ID:
        STORAGES = {
            "default": {
                "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
                "OPTIONS": {
                    "bucket_name": GCS_BUCKET_NAME,
                    "project_id": GCS_PROJECT_ID,
                    "credentials": GCS_CREDENTIALS,  # Dict from JSON or None for default auth
                    "default_acl": None,  # Use bucket's default ACL
                    "querystring_auth": True,  # Generate signed URLs for private files
                    "expiration": 3600,  # URL expiration in seconds (1 hour)
                    "file_overwrite": False,  # Don't overwrite files with same name
                    "location": "media",  # Prefix for all media files in bucket
                },
            },
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
            },
        }

        # Media URL will be served from GCS
        MEDIA_URL = f"https://storage.googleapis.com/{GCS_BUCKET_NAME}/media/"
    else:
        # Fallback to local storage if GCS is not properly configured
        logger.error(
            "GCS_PROJECT_ID is required but not set. Falling back to local file storage. "
            "File uploads in production will use local storage which is not recommended."
        )
        STORAGES = {
            "default": {
                "BACKEND": "django.core.files.storage.FileSystemStorage",
            },
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
            },
        }

        # Use local media URL as fallback
        MEDIA_URL = '/media/'

    # Keep MEDIA_ROOT for backwards compatibility (local storage fallback)
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Summary logging - verify credentials are properly configured
# Use simple boolean check without filesystem operations to avoid security issues
has_valid_credentials = (
    (GCS_CREDENTIALS and isinstance(GCS_CREDENTIALS, dict)) or 
    bool(GCS_CREDENTIALS_FILE)  # Just check if path is provided, not if file exists
)

if GCS_BUCKET_NAME and GCS_PROJECT_ID and has_valid_credentials:
    if DEBUG:
        logger.info(f"GCS credentials configured for development (backup/restore): bucket={GCS_BUCKET_NAME}")
    else:
        logger.info(f"GCS Storage fully configured: bucket={GCS_BUCKET_NAME}")
else:
    if DEBUG:
        logger.info("GCS credentials not configured - using local storage for media")
    else:
        logger.warning("GCS Storage partially configured - file uploads may not work")

# Private assets (certificates, fonts, etc.)
PRIVATE_ASSETS_PATH = os.path.join(BASE_DIR.parent, 'private_assets')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Upload Settings
# Allow larger files for video uploads (e.g., workout videos in fit app)
# Default Django limits are 2.5 MB which is too small for videos
# DATA_UPLOAD_MAX_MEMORY_SIZE controls the maximum size of a request body (default 2.5 MB)
# FILE_UPLOAD_MAX_MEMORY_SIZE controls when to stream to disk vs memory (default 2.5 MB)
# Files larger than FILE_UPLOAD_MAX_MEMORY_SIZE are streamed to temp files on disk
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB - max total request size
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760   # 10 MB - stream to disk for files > 10MB

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# CORS settings
CORS_ALLOW_CREDENTIALS = True

# Base CORS allowed origins
CORS_ALLOWED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = []
if DEBUG:
    # Development settings
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127.0.0.1:\d+$",
    ]
    CSRF_TRUSTED_ORIGINS.extend([
        "http://localhost",  # Traefik serves on port 80
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ])
else:
    # Production settings
    CORS_ALLOW_ALL_ORIGINS = False
    if DOMAIN:
        CORS_ALLOWED_ORIGINS.extend([
            f"https://{DOMAIN}",
            f"https://www.{DOMAIN}",
        ])
        CSRF_TRUSTED_ORIGINS.extend([
            f"https://{DOMAIN}",
            f"https://www.{DOMAIN}",
            f"https://api.{DOMAIN}",
        ])

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Cookie settings for API access
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF tokens

# Cookie settings - improved
if DEBUG:
    # Development - less strict
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_DOMAIN = None  # Explicitly set to None for localhost
    CSRF_COOKIE_DOMAIN = None
else:
    # Production - strict security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'  # Required for cross-site cookies
    CSRF_COOKIE_SAMESITE = 'None'
    # Only set domain if you need cross-subdomain cookies
    if DOMAIN:
        SESSION_COOKIE_DOMAIN = f".{DOMAIN}"  # Note the leading dot for subdomains
        CSRF_COOKIE_DOMAIN = f".{DOMAIN}"


# Debug prints
print(f"⊧ {DATABASES['default']['ENGINE']}")
print(f"⊧ DEBUG: {DEBUG} {ALLOWED_HOSTS}")


# ========================================
# REDIS CONFIGURATION
# ========================================
REDIS_HOST = os.getenv('REDIS_HOST', 'redis' if not DEBUG else 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_DB = int(os.getenv('REDIS_DB', 0))
REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Cache configuration using Redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'parser_class': 'redis.connection.HiredisParser',
            'pool_class': 'redis.BlockingConnectionPool',
            'pool_class_kwargs': {
                'max_connections': 50,
                'timeout': 20,
            },
        },
        'KEY_PREFIX': 'dientex',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Session backend using Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# ========================================
# CELERY CONFIGURATION
# ========================================
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = 'django-db'  # Store results in Django database
CELERY_CACHE_BACKEND = 'default'

# Celery settings
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task result settings
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 3600  # 1 hour
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

# Beat schedule for periodic tasks
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'send-appointment-reminders': {
        'task': 'notifications.tasks.send_appointment_reminders',
        'schedule': 3600.0,  # Every hour
    },
    'send-payment-reminders': {
        'task': 'notifications.tasks.send_payment_reminders',
        'schedule': 86400.0,  # Every day
    },
    'send-installment-reminders': {
        'task': 'notifications.tasks.send_installment_reminders',
        'schedule': 86400.0,  # Every day
    },
}


# ========================================
# THIRD-PARTY SERVICE CONFIGURATION
# ========================================

# SendGrid (Email)
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@dientex.com')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' if SENDGRID_API_KEY else 'django.core.mail.backends.console.EmailBackend'

# Twilio (SMS/WhatsApp)
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')
TWILIO_WHATSAPP_NUMBER = os.getenv('TWILIO_WHATSAPP_NUMBER', '')

# Stripe (Payments)
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Zoom (Telemedicine) - for future implementation
ZOOM_API_KEY = os.getenv('ZOOM_API_KEY', '')
ZOOM_API_SECRET = os.getenv('ZOOM_API_SECRET', '')

# Twilio Video (Alternative for Telemedicine)
TWILIO_VIDEO_API_KEY = os.getenv('TWILIO_VIDEO_API_KEY', '')
TWILIO_VIDEO_API_SECRET = os.getenv('TWILIO_VIDEO_API_SECRET', '')